name: base-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.49.0
  - jupyter-resource-usage=1.1.0
  - jupyterhub==5.3.0
  - jupyterlab==4.4.1
  - jupyter_server==2.15.0
  - jupyterlab-git==0.50.2
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.4.1
  - python==3.11.*
  - pip==25.1.1

  # r2d installs jupyter-rsession-proxy, but in the base python env, not in the updated one
  # - jupyter-rsession-proxy==2.3.0

  # vscode
  # - code-server==4.99.3
  # - jupyter-vscode-proxy==0.6
  # - jupyter-server-proxy==4.4.0

  # data science
  # - datascience==0.17.6
  # - matplotlib==3.10.1
  # - numpy==2.2.2
  # - openpyxl==3.1.5
  # - pandas==2.2.2
  # - plotly==6.0.0
  # - scikit-learn==1.6.1
  # - scipy==1.15.2
  # - seaborn==0.13.2
  # - statsmodels==0.14.4

  # pip installed packages, conda is preferred
  - pip:
    # r2d installs jupyter-shiny-proxy, but in the base python env, not in the updated one
    # - jupyter-shiny-proxy==1.3
    # - jupysql==0.10.15
    - nbconvert[webpdf]==7.16.4
    - otter-grader==6.1.3
