name: default-datahub-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:

# Items required for basic level functionality
- python==3.11.*
- git==2.46.0
- jupyter-resource-usage=1.1.0
- jupyterhub==4.1.6
- jupyterlab==4.2.5
- jupyter_server==2.14.2
- notebook==7.2.2
- nbgitpuller==1.2.1
 
- pip==24.2
- pip:
  - nbconvert[webpdf]==7.16.4
